---
- name: Initialize Runtime Variables
  set_fact:
    current_memory: "{{ memory_before.stdout | float }}"
    remediation_complete: false

- name: Remediation Attempt 1
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 1
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 2
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 2
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 3
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 3
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 4
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 4
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 5
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 5
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 6
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 6
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold

- name: Remediation Attempt 7
  include_tasks: remediation_attempt.yml
  vars:
    attempt_no: 7
  when:
    - not remediation_complete
    - current_memory | float > memory_threshold
